### ISSUE TITLE
Looks like a file is missing

### ISSUE THREAD

**Issue by metalpt** [jtara1/ExportHumbleBundleLibrary#1]
error: DevTools failed to parse SourceMap: chrome-extension://iebpjdmgckacbodjpijphcplhebcmeop/js/lib/FileSaver.min.js.map
Looks like the file doesn't exist.

**Comment by jtara1** [comment]
how did you install the extension? I haven't tested this old proj in a while. It should just be 2 local js files. I'm not sure what bundling or minifying chrome may do now with the js.

**Comment by jtara1** [comment]
stale issue and I didn't realize my ext on chrome app store was at version 0.1.0 for the longest time when 0.1.2 was available

1.0.0 is newest or check releases for this repo
