### ISSUE TITLE
No files created using Chrome Extension

### ISSUE THREAD

**Issue by SgtGerm** [jtara1/ExportHumbleBundleLibrary#2]
4main.js:28 Uncaught (in promise) TypeError: Cannot read property 'getAttribute' of undefined
    at getGamesList (main.js:28)
    at parseAndSaveGames (main.js:114)

I tried the chrome extensión , I get the button, screen change from page in the key library, but nothing else happends, error above is the only error codes I see when I press F12

Google Chrome
Version 81.0.4044.129 (Official Build) (64-bit)

**Comment by jtara1** [comment]
version 1.0.0 was sent for review to be published on the chrome app store

otherwise, it's available now by downloading this repo and loading dir w/ manifest.json file via chrome://extensions
